# Simple Neural Network
berikut ini adalah kasus sederhana pemodelan neuron dalam python

### Lihat Neuron Yuk
Gambar di bawah ini adalah koneksi dua neuron
![title](data/synapse.png)

### Modelnya Gmana?
Gambar di bawah ini adalah model dari satu buah neuron dengan 3 synapse input dan satu ouput
![title](data/perceptron.png)


### Kita mau nyobain apa ney?
|x0|x1|x2|y|
|-|-|-|-|
|1|0|0|0|
|1|0|1|1|
|1|1|0|1|
|1|1|1|1|


In [8]:
# numerical python
import numpy as np

In [9]:
# create data in python
train_input = np.array([
    [1, 0, 0], 
    [1, 1, 0], 
    [1, 0, 1], 
    [1, 1, 1]
])

train_output = np.array([
    [0],
    [1],
    [1],
    [1]
])

In [10]:
class NeuralNetwork():
    def __init__(self, neuron_in, neuron_out):
        np.random.seed(1)
        self.neuron_model = (neuron_in, neuron_out)
        self.synaptic_weights = 2 * np.random.random(self.neuron_model) - 1

    def activation(self, x, derivatives=False):
        if derivatives==True: 
            # gradient sigmoid curve (confident check)
            return x * (1 - x) 
        # S shape curve sigmoid, normalizer 0 to 1 (activation neuron)
        return 1 / (1 + np.exp(-x)) 
        
    def fit(self, train_input, train_output, iteration):
        for iteration in range(0, iteration):
            # Pass the training set through our neural network (a single neuron).
            output = self.predict(train_input)
            # check the error between thinking and true answer
            error = train_output - output
            # learn from error, and changes what suppose to be
            adjustment = np.dot(train_input.T, error * self.activation(output, True))
            # Adjust the weights.
            self.synaptic_weights += adjustment

    # The neural network thinks.
    def predict(self, inputs):
        # Pass inputs through our neural network (our single neuron).
        inp = np.dot(inputs, self.synaptic_weights)
        return self.activation(inp)

### Sigmoid? Apaan itu?
![title](data/sigmoid.png)

In [11]:
# def activation(x, derivatives=False):
#         if derivatives==True: 
#             # gradient sigmoid curve (confident check)
#             return x * (1 - x) 
#         # S shape curve sigmoid, normalizer 0 to 1 (activation neuron)
#         return 1 / (1 + np.exp(-x)) 

# activation(2)

In [12]:
# maksud rumus? otak atik yuks
np.random.random((3, 1))

array([[ 0.01440946],
       [ 0.81975787],
       [ 0.6690509 ]])

In [13]:
# lets build neural network
nn = NeuralNetwork(3,1)
syn_awal = nn.synaptic_weights

print("Bobot syanapse awal yang belum di training : ")
print(syn_awal)

Bobot syanapse awal yang belum di training : 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [14]:
# ingetin ulang inputnya
train_input

array([[1, 0, 0],
       [1, 1, 0],
       [1, 0, 1],
       [1, 1, 1]])

In [15]:
# ingetin ulang outputnya
train_output

array([[0],
       [1],
       [1],
       [1]])

In [16]:
# lets train the network
nn.fit(train_input, train_output, 60000)

print ("Setelah belajar, bobot synapse nya berubah: ")
print (nn.synaptic_weights)

Setelah belajar, bobot synapse nya berubah: 
[[ -5.02463281]
 [ 10.51123131]
 [ 10.51123127]]


In [19]:
# lets test it
test = np.array([1, 1, 0])
prediction = nn.predict(test)
print('Hasil Mikir :', prediction)

# pembulatan
print('Pembulatan  :', round(prediction[0]))

Hasil Mikir : [ 0.99587518]
Pembulatan  : 1.0


In [145]:
# test data yang lain, gmana kalau logika or
train_input = np.array([
    [0, 0, 1], 
    [1, 1, 1], 
    [1, 0, 1], 
    [0, 0, 0],
    [1, 0, 0]
])

train_output = np.array([
    [1],
    [1],
    [1],
    [0],
    [1]
])

In [122]:
# lets train the network
nn = NeuralNetwork(3,1)
nn.train(train_input, train_output, 60000)

In [127]:
test = np.array([0, 1, 0])
prediction = nn.thinking(test)
print('Hasil Mikir :', prediction)

#pembulatan
print('Pembulatan  :', round(prediction[0]))

Hasil Mikir : [ 0.69209135]
Pembulatan  : 1.0


In [124]:
# source code idea
# https://github.com/miloharper/simple-neural-network
# https://medium.com/technology-invention-and-more/how-to-build-a-simple-neural-network-in-9-lines-of-python-code-cc8f23647ca1