# Simple Neural Network
berikut ini adalah kasus sederhana pemodelan neuron dalam python

### Lihat Neuron Yuk
Gambar di bawah ini adalah koneksi dua neuron
![title](data/synapse.png)

### Modelnya Gmana?
Gambar di bawah ini adalah model dari satu buah neuron dengan 3 synapse input dan satu ouput
![title](data/neuron_model.png)


### Kita mau nyobain apa ney?

![title](data/truth_table.png)


In [46]:
# numerical python
import numpy as np

In [47]:
# create data in python
train_input = np.array([
    [0, 0, 1], 
    [1, 1, 1], 
    [1, 0, 1], 
    [0, 1, 1]
])

train_output = np.array([
    [0],
    [1],
    [1],
    [0]
])

![title](data/truth_matrix.png)

In [32]:
class NeuralNetwork():
    def __init__(self, neuron_in, neuron_out):
        np.random.seed(1)
        self.neuron_model = (neuron_in, neuron_out)
        self.synaptic_weights = 2 * np.random.random(self.neuron_model) - 1

    def sigmoid(self, x, derivatives=False):
        if derivatives==True: 
            # gradient sigmoid curve (confident check)
            return x * (1 - x) 
        # S shape curve, normalizer 0 to 1 (activation neuron)
        return 1 / (1 + np.exp(-x)) 
        
    def train(self, train_input, train_output, iteration):
        for iteration in range(0, iteration):
            # Pass the training set through our neural network (a single neuron).
            output = self.thinking(train_input)
            # check the error between thinking and true answer
            error = train_output - output
            # learn from error, and changes what suppose to be
            adjustment = np.dot(train_input.T, error * self.sigmoid(output, True))
            # Adjust the weights.
            self.synaptic_weights += adjustment

    # The neural network thinks.
    def thinking(self, inputs):
        # Pass inputs through our neural network (our single neuron).
        inp = np.dot(inputs, self.synaptic_weights)
        return self.sigmoid(inp)

In [62]:
# maksud rumus? 
2 * np.random.random((3, 1)) - 1

array([[-0.10421295],
       [ 0.81719101],
       [-0.4127717 ]])

In [66]:
# lets build neural network
nn = NeuralNetwork(3,1)
syn_awal = nn.synaptic_weights

print("Bobot syanapse awal yang belum di training : ")
print(syn_awal)

Bobot syanapse awal yang belum di training : 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [67]:
# ingetin ulang inputnya
train_input

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [68]:
# ingetin  ulang outputnya
train_output

array([[0],
       [1],
       [1],
       [0]])

In [74]:
# lets train the network
nn.train(train_input, train_output, 10000)

print ("Setelah belajar, bobot synapse nya berubah: ")
print (nn.synaptic_weights)

Setelah belajar, bobot synapse nya berubah: 
[[ 12.28064028]
 [ -0.2042021 ]
 [ -5.93641954]]


In [90]:
# lets test it
test = np.array([1, 0, 1])
prediction = nn.thinking(test)
print('Hasil Mikir :', prediction)

#pembulatan
print('Pembulatan  :', round(prediction[0]))

Hasil Mikir : [ 0.99824621]
Pembulatan  : 1.0


In [ ]:
# test data yang lain, gmana kalau logika or
train_input = np.array([
    [0, 0, 1], 
    [1, 1, 1], 
    [1, 0, 1], 
    [0, 1, 1]
])

train_output = np.array([
    [0],
    [1],
    [1],
    [0]
])

In [ ]:
# source code idea
# https://github.com/miloharper/simple-neural-network